Repository ChangePlusPlusVandy/UFAR-frontend, pull requests merged in 2022-05, with the labels that each got.

#65 Settings page on User's page and Admin's Page // Expiration Date for backend
  App.js
  components/daily-report-form/Bridge.js
  components/daily-report-form/SettingPage.js
  components/nurse-landing-page/Hamburger.js
  components/validation-page/Hamburger.js
  components/validation-page/Validation.js
  components/validation-page/pages/Dashboards.js
  components/validation-page/pages/SettingPage.js
  components/validation-page/pages/TokenGeneration.js
  src/context/AxiosContext.js
Labels: enhancement

#70 make DMMDay a date field
  components/daily-report-form/DailyReportForm.js
  components/daily-report-form/pages/DatesForm.js
  components/daily-report-form/pages/IdentificationForm.js
  components/nurse-landing-page/RecentsList.js
  components/validation-page/FetchButton.js
  components/validation-page/pages/RecentlyValidated.js
  components/validation-page/pages/ToBeValidated.js
  src/context/AxiosContext.js
Labels: enhancement

#73 Treatment Cycles Complete Feature - Parker
  components/daily-report-form/DailyReportForm.js
  components/daily-report-form/pages/TreatmentInformationForm.js
  components/validation-page/pages/RecentlyValidated.js
Labels: New Feature

#60 Drew small updates
  components/daily-report-form/DailyReportForm.js
  components/daily-report-form/pages/IdentificationForm.js
Labels: enhancement

#77 Export feature
  components/validation-page/Hamburger.js
  components/validation-page/Validation.js
  components/validation-page/pages/Archive.js
  components/validation-page/pages/Export.js
  components/validation-page/pages/ExportButton.js
  package-lock.json
  package.json
  yarn.lock
Labels: New Feature

#79 added date range filter for dashboards
  components/validation-page/Hamburger.js
  components/validation-page/pages/Dashboards.js
  components/validation-page/pages/DrugsUsedDashboard.js
  components/validation-page/pages/GeographicalDashboard.js
  components/validation-page/pages/TherapeuticalDashboard.js
  components/validation-page/pages/dateRangeFilter.js
Labels: New Feature

#84 Edit Without Fetching
  App.js
  components/daily-report-form/DailyReportForm.js
  components/nurse-landing-page/RecentsList.js
  src/actions.js
Labels: bug, enhancement
